### ISSUE TITLE
Performance issues: Stream stutters and freezes

### ISSUE THREAD

**Issue by Munzu** [akhanubis/twitch_chat_overlay_issues#17]
When I have the overlay enabled, my stream often stutters and/or freezes completely. I have to click the pause and play button for the stream to continue working again but the issue will return in a few seconds/minutes.

If I disable the overlay and refresh the page so that the overlay is not active, the problem is far less likely to occur. When I turn the overlay back on, the stuttering and freezing occurs very often. It feels a little bit as if I didn't have enough RAM or CPU power but both should be fine (16GB RAM, Ryzen 5 2600 and usage is low according to Task Manager.)

Might be confirmation bias but I think it's worse when chat is really fast and has a lot of animated emotes (BTTV and FFZ) like in forsen's chat.

**Comment by akhanubis** [comment]
Hi,

The extension adds another instance of the chat to the DOM and DOM handling for a fast chat with a lot of emotes and stuff can result in lag. 
Can you try adding the following to the url: `?force_vod=true` and check if performance improves? It moves the current chat around instead of creating another instance so it should perform better.

**Comment by Munzu** [comment]
Thanks for the quick reply!

Oh yeah, it's so much better now. Thanks! Is it possible to have this as a setting so I don't have to add it in the URL manually?

**Comment by akhanubis** [comment]
Added a global force_vod setting in 0.3.0, see #21
